/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErrorIndexRouteImport } from './routes/error/index'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as AppointmentsDailyDateRouteImport } from './routes/appointments/daily/$date'
import { Route as AppointmentsWeeklyDateAssistantIdRouteImport } from './routes/appointments/weekly/$date/$assistantId'
import { Route as AppointmentsDailyDateAppointmentIdRouteImport } from './routes/appointments/daily/$date/$appointmentId'
import { Route as AppointmentsWeeklyDateAssistantIdAppointmentIdRouteImport } from './routes/appointments/weekly/$date/$assistantId/$appointmentId'
import { Route as AppointmentsWeeklyDateAssistantIdNewTimeRouteImport } from './routes/appointments/weekly/$date/$assistantId/new/$time'
import { Route as AppointmentsDailyDateNewAssistantIdTimeRouteImport } from './routes/appointments/daily/$date/new/$assistantId/$time'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorIndexRoute = ErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsDailyDateRoute = AppointmentsDailyDateRouteImport.update({
  id: '/appointments/daily/$date',
  path: '/appointments/daily/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsWeeklyDateAssistantIdRoute =
  AppointmentsWeeklyDateAssistantIdRouteImport.update({
    id: '/appointments/weekly/$date/$assistantId',
    path: '/appointments/weekly/$date/$assistantId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppointmentsDailyDateAppointmentIdRoute =
  AppointmentsDailyDateAppointmentIdRouteImport.update({
    id: '/$appointmentId',
    path: '/$appointmentId',
    getParentRoute: () => AppointmentsDailyDateRoute,
  } as any)
const AppointmentsWeeklyDateAssistantIdAppointmentIdRoute =
  AppointmentsWeeklyDateAssistantIdAppointmentIdRouteImport.update({
    id: '/$appointmentId',
    path: '/$appointmentId',
    getParentRoute: () => AppointmentsWeeklyDateAssistantIdRoute,
  } as any)
const AppointmentsWeeklyDateAssistantIdNewTimeRoute =
  AppointmentsWeeklyDateAssistantIdNewTimeRouteImport.update({
    id: '/new/$time',
    path: '/new/$time',
    getParentRoute: () => AppointmentsWeeklyDateAssistantIdRoute,
  } as any)
const AppointmentsDailyDateNewAssistantIdTimeRoute =
  AppointmentsDailyDateNewAssistantIdTimeRouteImport.update({
    id: '/new/$assistantId/$time',
    path: '/new/$assistantId/$time',
    getParentRoute: () => AppointmentsDailyDateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/error': typeof ErrorIndexRoute
  '/appointments/daily/$date': typeof AppointmentsDailyDateRouteWithChildren
  '/appointments/daily/$date/$appointmentId': typeof AppointmentsDailyDateAppointmentIdRoute
  '/appointments/weekly/$date/$assistantId': typeof AppointmentsWeeklyDateAssistantIdRouteWithChildren
  '/appointments/weekly/$date/$assistantId/$appointmentId': typeof AppointmentsWeeklyDateAssistantIdAppointmentIdRoute
  '/appointments/daily/$date/new/$assistantId/$time': typeof AppointmentsDailyDateNewAssistantIdTimeRoute
  '/appointments/weekly/$date/$assistantId/new/$time': typeof AppointmentsWeeklyDateAssistantIdNewTimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/error': typeof ErrorIndexRoute
  '/appointments/daily/$date': typeof AppointmentsDailyDateRouteWithChildren
  '/appointments/daily/$date/$appointmentId': typeof AppointmentsDailyDateAppointmentIdRoute
  '/appointments/weekly/$date/$assistantId': typeof AppointmentsWeeklyDateAssistantIdRouteWithChildren
  '/appointments/weekly/$date/$assistantId/$appointmentId': typeof AppointmentsWeeklyDateAssistantIdAppointmentIdRoute
  '/appointments/daily/$date/new/$assistantId/$time': typeof AppointmentsDailyDateNewAssistantIdTimeRoute
  '/appointments/weekly/$date/$assistantId/new/$time': typeof AppointmentsWeeklyDateAssistantIdNewTimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/error/': typeof ErrorIndexRoute
  '/appointments/daily/$date': typeof AppointmentsDailyDateRouteWithChildren
  '/appointments/daily/$date/$appointmentId': typeof AppointmentsDailyDateAppointmentIdRoute
  '/appointments/weekly/$date/$assistantId': typeof AppointmentsWeeklyDateAssistantIdRouteWithChildren
  '/appointments/weekly/$date/$assistantId/$appointmentId': typeof AppointmentsWeeklyDateAssistantIdAppointmentIdRoute
  '/appointments/daily/$date/new/$assistantId/$time': typeof AppointmentsDailyDateNewAssistantIdTimeRoute
  '/appointments/weekly/$date/$assistantId/new/$time': typeof AppointmentsWeeklyDateAssistantIdNewTimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/tanstack-query'
    | '/appointments'
    | '/error'
    | '/appointments/daily/$date'
    | '/appointments/daily/$date/$appointmentId'
    | '/appointments/weekly/$date/$assistantId'
    | '/appointments/weekly/$date/$assistantId/$appointmentId'
    | '/appointments/daily/$date/new/$assistantId/$time'
    | '/appointments/weekly/$date/$assistantId/new/$time'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/tanstack-query'
    | '/appointments'
    | '/error'
    | '/appointments/daily/$date'
    | '/appointments/daily/$date/$appointmentId'
    | '/appointments/weekly/$date/$assistantId'
    | '/appointments/weekly/$date/$assistantId/$appointmentId'
    | '/appointments/daily/$date/new/$assistantId/$time'
    | '/appointments/weekly/$date/$assistantId/new/$time'
  id:
    | '__root__'
    | '/'
    | '/demo/tanstack-query'
    | '/appointments/'
    | '/error/'
    | '/appointments/daily/$date'
    | '/appointments/daily/$date/$appointmentId'
    | '/appointments/weekly/$date/$assistantId'
    | '/appointments/weekly/$date/$assistantId/$appointmentId'
    | '/appointments/daily/$date/new/$assistantId/$time'
    | '/appointments/weekly/$date/$assistantId/new/$time'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  ErrorIndexRoute: typeof ErrorIndexRoute
  AppointmentsDailyDateRoute: typeof AppointmentsDailyDateRouteWithChildren
  AppointmentsWeeklyDateAssistantIdRoute: typeof AppointmentsWeeklyDateAssistantIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/': {
      id: '/error/'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/daily/$date': {
      id: '/appointments/daily/$date'
      path: '/appointments/daily/$date'
      fullPath: '/appointments/daily/$date'
      preLoaderRoute: typeof AppointmentsDailyDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/weekly/$date/$assistantId': {
      id: '/appointments/weekly/$date/$assistantId'
      path: '/appointments/weekly/$date/$assistantId'
      fullPath: '/appointments/weekly/$date/$assistantId'
      preLoaderRoute: typeof AppointmentsWeeklyDateAssistantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/daily/$date/$appointmentId': {
      id: '/appointments/daily/$date/$appointmentId'
      path: '/$appointmentId'
      fullPath: '/appointments/daily/$date/$appointmentId'
      preLoaderRoute: typeof AppointmentsDailyDateAppointmentIdRouteImport
      parentRoute: typeof AppointmentsDailyDateRoute
    }
    '/appointments/weekly/$date/$assistantId/$appointmentId': {
      id: '/appointments/weekly/$date/$assistantId/$appointmentId'
      path: '/$appointmentId'
      fullPath: '/appointments/weekly/$date/$assistantId/$appointmentId'
      preLoaderRoute: typeof AppointmentsWeeklyDateAssistantIdAppointmentIdRouteImport
      parentRoute: typeof AppointmentsWeeklyDateAssistantIdRoute
    }
    '/appointments/weekly/$date/$assistantId/new/$time': {
      id: '/appointments/weekly/$date/$assistantId/new/$time'
      path: '/new/$time'
      fullPath: '/appointments/weekly/$date/$assistantId/new/$time'
      preLoaderRoute: typeof AppointmentsWeeklyDateAssistantIdNewTimeRouteImport
      parentRoute: typeof AppointmentsWeeklyDateAssistantIdRoute
    }
    '/appointments/daily/$date/new/$assistantId/$time': {
      id: '/appointments/daily/$date/new/$assistantId/$time'
      path: '/new/$assistantId/$time'
      fullPath: '/appointments/daily/$date/new/$assistantId/$time'
      preLoaderRoute: typeof AppointmentsDailyDateNewAssistantIdTimeRouteImport
      parentRoute: typeof AppointmentsDailyDateRoute
    }
  }
}

interface AppointmentsDailyDateRouteChildren {
  AppointmentsDailyDateAppointmentIdRoute: typeof AppointmentsDailyDateAppointmentIdRoute
  AppointmentsDailyDateNewAssistantIdTimeRoute: typeof AppointmentsDailyDateNewAssistantIdTimeRoute
}

const AppointmentsDailyDateRouteChildren: AppointmentsDailyDateRouteChildren = {
  AppointmentsDailyDateAppointmentIdRoute:
    AppointmentsDailyDateAppointmentIdRoute,
  AppointmentsDailyDateNewAssistantIdTimeRoute:
    AppointmentsDailyDateNewAssistantIdTimeRoute,
}

const AppointmentsDailyDateRouteWithChildren =
  AppointmentsDailyDateRoute._addFileChildren(
    AppointmentsDailyDateRouteChildren,
  )

interface AppointmentsWeeklyDateAssistantIdRouteChildren {
  AppointmentsWeeklyDateAssistantIdAppointmentIdRoute: typeof AppointmentsWeeklyDateAssistantIdAppointmentIdRoute
  AppointmentsWeeklyDateAssistantIdNewTimeRoute: typeof AppointmentsWeeklyDateAssistantIdNewTimeRoute
}

const AppointmentsWeeklyDateAssistantIdRouteChildren: AppointmentsWeeklyDateAssistantIdRouteChildren =
  {
    AppointmentsWeeklyDateAssistantIdAppointmentIdRoute:
      AppointmentsWeeklyDateAssistantIdAppointmentIdRoute,
    AppointmentsWeeklyDateAssistantIdNewTimeRoute:
      AppointmentsWeeklyDateAssistantIdNewTimeRoute,
  }

const AppointmentsWeeklyDateAssistantIdRouteWithChildren =
  AppointmentsWeeklyDateAssistantIdRoute._addFileChildren(
    AppointmentsWeeklyDateAssistantIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  ErrorIndexRoute: ErrorIndexRoute,
  AppointmentsDailyDateRoute: AppointmentsDailyDateRouteWithChildren,
  AppointmentsWeeklyDateAssistantIdRoute:
    AppointmentsWeeklyDateAssistantIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
